name = input('What is Your name? ')
age = int(input('How old are You (complete)? '))
city = input('What city do you live in? ')
print()
print('This is', name)
print('It is', age)
print('(S)he live in', city)
